export const PRODUCTS_LIST_REQUESTS = 'PRODUCTS_LIST_REQUESTS'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAILED = 'PRODUCTS_LIST_FAILED'


export const PRODUCT_CREATE_REQUESTS = 'PRODUCT_CREATE_REQUESTS'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED'
export const PRODUCT_CREATE_REFRESH = 'PRODUCT_CREATE_REFRESH'