export const PROJECTS_LIST_REQUESTS = 'PROJECTS_LIST_REQUESTS'
export const PROJECTS_LIST_SUCCESS = 'PROJECTS_LIST_SUCCESS'
export const PROJECTS_LIST_FAILED = 'PROJECTS_LIST_FAILED'



export const PROJECT_CREATE_REQUESTS = 'PROJECT_CREATE_REQUESTS'
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAILED = 'PROJECT_CREATE_FAILED'
export const PROJECT_CREATE_REFRESH = 'PROJECT_CREATE_REFRESH'