export const TRANSACTIONS_REQUESTS = 'TRANSACTIONS_REQUESTS'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS'
export const TRANSACTIONS_FAILED = 'TRANSACTIONS_FAILED'
export const TRANSACTIONS_REFRESH = 'TRANSACTIONS_REFRESH'