export const TRANSACTIONS_REQUESTS = 'TRANSACTIONS_REQUESTS'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS'
export const TRANSACTIONS_FAILED = 'TRANSACTIONS_FAILED'
export const TRANSACTIONS_REFRESH = 'TRANSACTIONS_REFRESH'


export const MY_TRANSACTIONS_REQUESTS = 'MY_TRANSACTIONS_REQUESTS'
export const MY_TRANSACTIONS_SUCCESS = 'MY_TRANSACTIONS_SUCCESS'
export const MY_TRANSACTIONS_FAILED = 'MY_TRANSACTIONS_FAILED'