const USER_LOGIN_REQUESTS = 'USER_LOGIN_REQUESTS'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
const USER_REFRESH = 'USER_REFRESH'
const USER_DETAILS_REQUESTS = 'USER_DETAILS_REQUESTS'
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED'
export {
    USER_LOGIN_REQUESTS,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_REFRESH,
    USER_DETAILS_REQUESTS,
    USER_DETAILS_SUCCESS,
    USER_DETAILS_FAILED

}