const USER_LOGIN_REQUESTS = 'USER_LOGIN_REQUESTS'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
const USER_REFRESH = 'USER_REFRESH'

export {
    USER_LOGIN_REQUESTS,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_REFRESH,

}